Step 1: import Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Step 2: Load Dataset

In [3]:
data = pd.read_csv("C:\\Tekworks\\Day 13 - tasks\\train (1).csv")
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

Step 3: Select Important Columns

In [5]:
important_columns = [
    "SalePrice",
    "OverallQual",
    "GrLivArea",
    "GarageCars",
    "TotalBsmtSF",
    "YearBuilt",
    "Neighborhood",
    "LotArea",
    "KitchenQual"
]

data = data[important_columns]
data

,SalePrice,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,Neighborhood,LotArea,KitchenQual
0,208500,7,1710,2,856,2003,CollgCr,8450,Gd
1,181500,6,1262,2,1262,1976,Veenker,9600,TA
2,223500,7,1786,2,920,2001,CollgCr,11250,Gd
3,140000,7,1717,3,756,1915,Crawfor,9550,Gd
4,250000,8,2198,3,1145,2000,NoRidge,14260,Gd
...,...,...,...,...,...,...,...,...,...
1455,175000,6,1647,2,953,1999,Gilbert,7917,TA
1456,210000,6,2073,2,1542,1978,NWAmes,13175,TA
1457,266500,7,2340,1,1152,1941,Crawfor,9042,Gd
1458,142125,5,1078,1,1078,1950,NAmes,9717,Gd
1459,147500,5,1256,1,1256,1965,Edwards,9937,TA

Step 4: Handle Missing Values

In [6]:
data["GarageCars"].fillna(data["GarageCars"].median(), inplace=True)
data["TotalBsmtSF"].fillna(data["TotalBsmtSF"].median(), inplace=True)
data["KitchenQual"].fillna(data["KitchenQual"].mode()[0], inplace=True)

C:\Users\MAHIPALREDDY\AppData\Local\Temp\ipykernel_24100\3080849074.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["GarageCars"].fillna(data["GarageCars"].median(), inplace=True)
C:\Users\MAHIPALREDDY\AppData\Local\Temp\ipykernel_24100\3080849074.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["TotalBsmtSF"].fillna(data["TotalBsmtSF"].median(), inplace=True)
C:\Users\MAHIPALREDDY\AppData\Local\Temp\ipykernel_24100\3080849074.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["KitchenQual"].fillna(data["KitchenQual"].mode()[0], inplace=True)

Step 5: Convert Categorical Columns to Numeric

In [ ]:
data = pd.get_dummies(data, columns=["Neighborhood","KitchenQual"], drop_first=True)

In [12]:
data.columns

Index(['SalePrice', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF',
       'YearBuilt', 'LotArea', 'Neighborhood_Blueste', 'Neighborhood_BrDale',
       'Neighborhood_BrkSide', 'Neighborhood_ClearCr', 'Neighborhood_CollgCr',
       'Neighborhood_Crawfor', 'Neighborhood_Edwards', 'Neighborhood_Gilbert',
       'Neighborhood_IDOTRR', 'Neighborhood_MeadowV', 'Neighborhood_Mitchel',
       'Neighborhood_NAmes', 'Neighborhood_NPkVill', 'Neighborhood_NWAmes',
       'Neighborhood_NoRidge', 'Neighborhood_NridgHt', 'Neighborhood_OldTown',
       'Neighborhood_SWISU', 'Neighborhood_Sawyer', 'Neighborhood_SawyerW',
       'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Timber',
       'Neighborhood_Veenker', 'KitchenQual_Fa', 'KitchenQual_Gd',
       'KitchenQual_TA'],
      dtype='object')

Step 6: Split Input and Output

In [15]:
X = data.drop("SalePrice", axis=1)
y = data["SalePrice"]

In [18]:
X

,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,LotArea,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,...,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA
0,7,1710,2,856,2003,8450,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,6,1262,2,1262,1976,9600,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
2,7,1786,2,920,2001,11250,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,7,1717,3,756,1915,9550,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,8,2198,3,1145,2000,14260,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,6,1647,2,953,1999,7917,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1456,6,2073,2,1542,1978,13175,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1457,7,2340,1,1152,1941,9042,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1458,5,1078,1,1078,1950,9717,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1459,5,1256,1,1256,1965,9937,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [19]:
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

Step 7: Train Test Split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
X_train
X_test
y_train
y_test

892     154500
1105    325000
413     115000
522     159000
1036    315500
         ...
479      89471
1361    260000
802     189000
651     108000
722     124500
Name: SalePrice, Length: 292, dtype: int64

Step 8: Train Linear Regression Model

In [22]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

Step 9: Prediction

In [23]:
y_pred = model.predict(X_test)

In [24]:
y_pred

array([136738.57212623, 321500.28622004, 111114.74843112, 170831.1954036 ,
       307589.1803193 ,  60821.34422285, 230776.95039826, 150712.29800276,
        60527.57423882, 124587.91601117, 147715.47942234, 111327.59023897,
       103021.93596838, 247166.66285741, 181269.66404646, 125526.96892153,
       204497.97608592, 122593.26519003, 115006.71906131, 208824.27647713,
       168668.60635465, 222598.47116151, 185240.908807  , 111415.61551157,
       204395.20103789, 169567.32590321, 196673.36856817, 112839.87463578,
       178481.81057797, 204495.07433968, 124204.23185543, 273037.04582224,
       281927.72189605, 101041.98689798, 250162.96289319, 139963.26291011,
       155175.33660817, 217841.42532745, 328096.12096179,  89632.71240207,
       144722.84102879, 218190.21704505, 118702.23340164, 348341.25243444,
       131467.15287301, 151116.29381981, 113449.83960696, 118134.04930024,
       380694.47435892, 139174.33426359, 111888.7540663 , 186352.20201851,
       110352.17362156, 283809.60894486, 157505.50685415, 224649.01628464,
       201130.98814346, 199699.60914608, 141026.33149117,  94258.11886325,
        75228.54618008, 139721.89948079, 305565.62223544, 290831.98146215,
       258626.29915427, 192048.86021801, 100316.85823234, 272983.65361268,
       112445.97998213, 175807.66363703, 140661.65949563, 129754.35316662,
        98864.14249265,  88570.35357678, 379178.95342398, 197370.89943868,
       321596.19220581, 308215.44290314, 125506.12840003, 112918.17295277,
       105033.18507246, 104633.55623208, 132597.29927519,  83316.60155416,
       160757.41112171, 134510.32482453, 253925.83050968, 217916.57989485,
       157503.72320371, 198827.25123978, 146566.0015987 , 156085.33406791,
       111200.42026574, 250745.82429155, 141766.97122305, 182740.5343771 ,
       227765.5642372 , 197235.2948578 , 210096.03585689, 272480.75841372,
       183940.98722245, 211582.01303748, 230276.35242834, 142714.57457732,
       210327.31796181, 168026.67475312, 154802.29088026, 272187.60951853,
       143635.20903395, 181178.75035142,  48649.05995427, 118360.04133605,
       121288.515192  , 132292.25528843, 215057.51408288,  98696.86245564,
        85651.50255619, 135131.43145217, 173200.44552387, 299116.17446217,
       137603.67107268, 157505.50685415, 176945.0435173 , 183383.84104033,
       193995.64630341, 120170.56662796, 227889.25588555, 109716.18462758,
       147725.36291113, 185878.37532276, 202517.31669663, 268582.63570979,
       211731.90687638, 141714.90076698,  42375.40675916, 354832.78502364,
       339729.66765282, 123817.97818109, 228791.84015355, 494844.15184332,
       387742.00412865, 115385.03687328, 184209.0386388 , 160499.98086824,
       146784.00549419, 113133.30395829, 223304.53024711, 208981.17530581,
       112244.25996016,  49394.93852363, 131901.96764726, 153149.13499789,
       264948.58549302, 186322.62617496,  80676.87534555, 142296.93921691,
       136960.41065025, 163023.16023654,  48776.93377619, 124784.66747333,
       209595.47267397, 139407.01290243, 248667.41307924, 131644.74009354,
       120818.18261247, 151034.88302213, 223834.30402348, 325736.43464934,
       404245.17482511, 229814.24184706, 353399.80547075,  73279.63250896,
       113724.85531698, 140348.64123206, 333624.6513348 , 155273.61383422,
       132860.60893474, 218317.88818082, 127431.769697  , 189743.57422078,
       154487.41067362, 119143.24383072, 136900.51498461, 137425.50082356,
       237885.56255232, 158624.69000165, 237752.29377976, 198608.16923044,
       236406.50588517,  90453.00087983, 114439.04069055,  98563.67434318,
       152918.59448063, 140210.71337138, 219166.62865636, 199076.88482249,
       210597.91592344,  97303.42066734, 225415.44071603, 147992.08315258,
       258275.52588865, 188166.6665561 , 112888.10202911, 332801.25196814,
       199895.79559457, 119265.56988338, 230571.34274636, 138823.45289146,
       145578.87236124, 113491.04231188, 233519.41564041, 155668.15636523,
       102307.18898559, 176356.19365992, 215262.31439471, 232729.70987628,
       193031.41678943, 125298.7838357 , 164153.9648205 , 158875.62403962,
       131422.90824201, 246611.73212651, 210022.14783126, 101240.64101229,
       238316.67924408, 144348.21044992, 100984.27389472,  80373.35208664,
       176955.92481684,  88913.57329222,  84220.49513462, 177034.96725664,
       130991.28962758, 109966.53254683, 222357.77416924, 136968.05393363,
       192764.31987504, 157749.6896336 , 211579.95504453, 129854.47907194,
       105596.06540862, 247005.90403861, 203478.8023516 , 365616.89746892,
       190889.28978553,  97093.68755188, 151026.73270229, 179602.38154056,
       123386.18553529,  90508.7850634 , 181651.54337367, 185546.67891017,
       138554.03724917, 131360.27873519, 130906.54730113, 138140.46764204,
       114729.97359975,  98466.10145441, 179778.82435156, 241544.80586624,
       298842.51912463, 199289.57386585, 122488.23398719, 207422.23540782,
       285866.74803906, 227801.47668858, 165650.22264369, 157224.55080406,
       117903.37108838, 175394.14948673, 376042.40181056, 250981.99064389,
       230234.1085635 , 106005.83027108, 113278.12952058, 132309.95495701,
       191760.33022725, 336698.97877621, 233527.67226332, 137278.19344763,
       215843.49637583, 127638.81575554, 208134.92843884,  94527.7430446 ,
       247916.04386454, 181117.64411375, 217433.54133211, 102215.44210626,
       258747.7984634 , 196821.50521418, 107274.10680364, 111363.2174468 ])

Step 10: Model Evaluation

In [25]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R2 Score:", r2)

RMSE: 34478.41679427924
R2 Score: 0.8450181657820286